import { useMemo, useState } from 'react';
import { Card, TrackRow } from '../components/common';
import { art, Spotify } from '../lib/api';
import { playTracks, useStore } from '../lib/store';
import { useLoad } from './hooks';

const RANGES = { short_term: '4 weeks', medium_term: '6 months', long_term: 'All time' } as const;
type Range = keyof typeof RANGES;

export function Stats() {
  const go = useStore((s) => s.go);
  const notify = useStore((s) => s.notify);
  const [range, setRange] = useState<Range>('short_term');
  const tracks = useLoad(`top-tracks-${range}`, () => Spotify.top('tracks', range));
  const artistsQ = useLoad(`top-artists-${range}`, () => Spotify.top('artists', range));
  const recent = useLoad('recent', Spotify.recent);

  const genres = useMemo(() => {
    const m = new Map<string, number>();
    artistsQ.data?.items.forEach((a, i) => a.genres?.forEach((g) => m.set(g, (m.get(g) ?? 0) + (50 - i))));
    return [...m].sort((a, b) => b[1] - a[1]).slice(0, 8);
  }, [artistsQ.data]);
  const maxG = genres[0]?.[1] ?? 1;

  const clock = useMemo(() => {
    const h = Array(24).fill(0) as number[];
    recent.data?.items.forEach((i) => h[new Date(i.played_at).getHours()]++);
    return h;
  }, [recent.data]);
  const maxC = Math.max(1, ...clock);
  const peak = clock.indexOf(maxC);
  const mins = Math.round((recent.data?.items.reduce((s, i) => s + i.track.duration_ms, 0) ?? 0) / 60000);

  const saveTop = async () => {
    if (!tracks.data) return;
    try {
      const pl = await Spotify.createPlaylist(`My Top Tracks · ${RANGES[range]}`, 'Generated by RY Music');
      await Spotify.addToPlaylist(pl.id, tracks.data.items.map((t) => t.uri));
      notify('Playlist created');
    } catch (e) {
      notify((e as Error).message);
    }
  };

  return (
    <div className="view stats">
      <h1>Your Sound DNA</h1>
      <div className="seg wide">
        {(Object.keys(RANGES) as Range[]).map((r) => (
          <button key={r} className={r === range ? 'on' : ''} onClick={() => setRange(r)}>
            {RANGES[r]}
          </button>
        ))}
      </div>

      <div className="stat-tiles">
        <div className="tile">
          <small>Last 50 plays</small>
          <strong>{mins} min</strong>
        </div>
        <div className="tile">
          <small>Peak hour</small>
          <strong>{recent.data ? `${peak}:00` : '—'}</strong>
        </div>
        <div className="tile">
          <small>#1 artist</small>
          <strong>{artistsQ.data?.items[0]?.name ?? '—'}</strong>
        </div>
      </div>

      <section className="panel-card">
        <h2>Listening clock</h2>
        <div className="clock">
          {clock.map((v, h) => (
            <div key={h} className="clock-bar" title={`${h}:00 — ${v} plays`}>
              <i style={{ height: `${(v / maxC) * 100}%` }} />
              {h % 6 === 0 && <span>{h}</span>}
            </div>
          ))}
        </div>
      </section>

      {genres.length > 0 && (
        <section className="panel-card">
          <h2>Your sound</h2>
          {genres.map(([g, v]) => (
            <div key={g} className="genre">
              <span>{g}</span>
              <div>
                <i style={{ width: `${(v / maxG) * 100}%` }} />
              </div>
            </div>
          ))}
        </section>
      )}

      <h2>Top artists</h2>
      <div className="shelf-row">
        {artistsQ.data?.items.slice(0, 20).map((a, i) => (
          <Card key={a.id} round img={art(a.images)} title={`${i + 1}. ${a.name}`} onClick={() => go({ name: 'artist', id: a.id, title: a.name })} />
        ))}
      </div>

      <div className="queue-head">
        <h2>Top tracks</h2>
        <button className="chip" onClick={saveTop}>
          Save as playlist
        </button>
      </div>
      {tracks.data?.items.map((t, i) => (
        <TrackRow key={t.id} track={t} index={i} onPlay={() => playTracks(tracks.data!.items, i)} />
      ))}
    </div>
  );
}
